CREATE TABLE persons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK ( name <> '' ),
    surname TEXT NOT NULL CHECK ( surname <> '' ),
    patronymic TEXT,
    age SMALLINT NOT NULL CHECK (age >= 0),
    gender SMALLINT NOT NULL CHECK (gender >= 0),
    nationality TEXT NOT NULL CHECK ( nationality <> '' )
);
